---
title: "LA 1"
author: "Kishor Kumar Naik P"
date: "2022-09-24"
output: html_document
---

```{r}
df1 = read.csv('banned_maps_stats.csv')
df1
```
```{r}
df2 = read.csv('side_pick_stats.csv')
df2
```
```{r}
df3 = read.csv('map_pick_stats.csv')
df3
```
```{r}
df4 = read.csv('player_stats.csv')
df4
```


```{r}
df1$Map
```
```{r}
df1$Total
```
```{r}
df1$Day1
```
```{r}
df1$Day2
```
```{r}
df1$Day3
```
```{r}
df1$Day4
```
```{r}
df1$Day5
```
```{r}
df1$Day6
```
```{r}
df1$Day7
```


```{r}
df2$Map
```
```{r}
df2$AtkWins
```
```{r}
df2$DefWins
```

```{r}
df3$Map
```
```{r}
df3$Total
```
```{r}
df3$Day1
```
```{r}
df3$Day2
```
```{r}
df3$Day3
```
```{r}
df3$Day4
```
```{r}
df3$Day5
```
```{r}
df3$Day6
```
```{r}
df3$Day7
```


```{r}
df4$Player
```
```{r}
df4$Country
```
```{r}
df4$Team
```
```{r}
df4$Agents
```
```{r}
df4$Maps
```
```{r}
df4$K
```
```{r}
df4$D
```
```{r}
df4$A
```
```{r}
df4$KD
```
```{r}
df4$KDA
```


```{r}
data.frame(df1)
```
```{r}
data.frame(df2)
```
```{r}
data.frame(df3)
```
```{r}
data.frame(df4)
```

```{r}
View(df1)
```
```{r}
View(df2)
```
```{r}
View(df3)
```
```{r}
View(df4)
```

```{r}
names(df1)
```
```{r}
names(df2)
```
```{r}
names(df3)
```
```{r}
names(df4)
```
```{r}
row.names(df1)
```
```{r}
row.names(df2)
```
```{r}
row.names(df3)
```
```{r}
row.names(df4)
```
```{r}
colnames(df1)
```
```{r}
colnames(df2)
```
```{r}
colnames(df3)
```
```{r}
colnames(df4)
```

```{r}
length(df1)
```
```{r}
length(df2)
```
```{r}
length(df3)
```
```{r}
length(df4)
```

```{r}
str(df1)
```
```{r}
str(df2)
```
```{r}
str(df3)
```
```{r}
str(df4)
```
```{r}
ls(df1)
```
```{r}
ls(df2)
```
```{r}
ls(df3)
```
```{r}
ls(df4)
```

```{r}
ls.str(df1)
```
```{r}
ls.str(df2)
```
```{r}
ls.str(df3)
```
```{r}
ls.str(df4)
```

```{r}
ls.str(pattern = 'df1')
```
```{r}
ls.str(pattern = 'df2')
```
```{r}
ls.str(pattern = 'df3')
```
```{r}
ls.str(pattern = 'df4')
```

```{r}
dim(df1)
```
```{r}
dim(df2)
```
```{r}
dim(df3)
```
```{r}
dim(df4)
```
```{r}
dimnames(df1)
```
```{r}
dimnames(df2)
```
```{r}
dimnames(df3)
```
```{r}
dimnames(df4)
```
```{r}
head(df1)
```
```{r}
head(df2)
```
```{r}
head(df3)
```
```{r}
head(df4)
```


```{r}
head(df1$Map)
```
```{r}
head(df1$Total)
```
```{r}
head(df1$Day1)
```
```{r}
head(df1$Day2)
```
```{r}
head(df1$Day3)
```
```{r}
head(df1$Day4)
```
```{r}
head(df1$Day5)
```
```{r}
head(df1$Day6)
```
```{r}
head(df1$Day7)
```
```{r}
head(df2$Map)
```
```{r}
head(df2$AtkWins)
```
```{r}
head(df2$DefWins)
```

```{r}
head(df3$Map)
```
```{r}
head(df3$Total)
```
```{r}
head(df3$Day1)
```
```{r}
head(df3$Day2)
```
```{r}
head(df3$Day3)
```
```{r}
head(df3$Day4)
```
```{r}
head(df3$Day5)
```
```{r}
head(df3$Day6)
```
```{r}
head(df3$Day7)
```

```{r}
head(df4$Player)
```
```{r}
head(df4$Country)
```
```{r}
head(df4$Team)
```
```{r}
head(df4$Agents)
```
```{r}
head(df4$Maps)
```
```{r}
head(df4$K)
```
```{r}
head(df4$D)
```
```{r}
head(df4$A)
```
```{r}
head(df4$KD)
```
```{r}
head(df4$KDA)
```


```{r}
head(structure(df1))
```
```{r}
head(structure(df2))
```
```{r}
head(structure(df3))
```
```{r}
head(structure(df4))
```


```{r}
tail(df1)
```
```{r}
tail(df2)
```
```{r}
tail(df3)
```
```{r}
tail(df4)
```


```{r}
tail(df1$Map)
```
```{r}
tail(df1$Total)
```
```{r}
tail(df1$Day1)
```
```{r}
tail(df1$Day2)
```
```{r}
tail(df1$Day3)
```
```{r}
tail(df1$Day4)
```
```{r}
tail(df1$Day5)
```
```{r}
tail(df1$Day6)
```
```{r}
tail(df1$Day7)
```
```{r}
tail(df2$Map)
```
```{r}
tail(df2$AtkWins)
```
```{r}
tail(df2$DefWins)
```

```{r}
tail(df3$Map)
```
```{r}
tail(df3$Total)
```
```{r}
tail(df3$Day1)
```
```{r}
tail(df3$Day2)
```
```{r}
tail(df3$Day3)
```
```{r}
tail(df3$Day4)
```
```{r}
tail(df3$Day5)
```
```{r}
tail(df3$Day6)
```
```{r}
tail(df3$Day7)
```

```{r}
tail(df4$Player)
```
```{r}
tail(df4$Country)
```
```{r}
tail(df4$Team)
```
```{r}
tail(df4$Agents)
```
```{r}
tail(df4$Maps)
```
```{r}
tail(df4$K)
```
```{r}
tail(df4$D)
```
```{r}
tail(df4$A)
```
```{r}
tail(df4$KD)
```
```{r}
tail(df4$KDA)
```

```{r}
tail(structure(df1))
```
```{r}
tail(structure(df2))
```
```{r}
tail(structure(df3))
```
```{r}
tail(structure(df4))
```


```{r}
class(df1)
```
```{r}
class(df2)
```
```{r}
class(df3)
```
```{r}
class(df4)
```



```{r}
class(df1$Map)
```
```{r}
class(df1$Total)
```
```{r}
class(df1$Day1)
```
```{r}
class(df1$Day2)
```
```{r}
class(df1$Day3)
```
```{r}
class(df1$Day4)
```
```{r}
class(df1$Day5)
```
```{r}
class(df1$Day6)
```
```{r}
class(df1$Day7)
```
```{r}
class(df2$Map)
```
```{r}
class(df2$AtkWins)
```
```{r}
class(df2$DefWins)
```

```{r}
class(df3$Map)
```
```{r}
class(df3$Total)
```
```{r}
class(df3$Day1)
```
```{r}
class(df3$Day2)
```
```{r}
class(df3$Day3)
```
```{r}
class(df3$Day4)
```
```{r}
class(df3$Day5)
```
```{r}
class(df3$Day6)
```
```{r}
class(df3$Day7)
```

```{r}
class(df4$Player)
```
```{r}
class(df4$Country)
```
```{r}
class(df4$Team)
```
```{r}
class(df4$Agents)
```
```{r}
class(df4$Maps)
```
```{r}
class(df4$K)
```
```{r}
class(df4$D)
```
```{r}
class(df4$A)
```
```{r}
class(df4$KD)
```
```{r}
class(df4$KDA)
```


```{r}
class(structure(df1))
```
```{r}
class(structure(df2))
```
```{r}
class(structure(df3))
```
```{r}
class(structure(df4))
```


```{r}
class(dim(df1))
```
```{r}
class(dim(df2))
```
```{r}
class(dim(df3))
```
```{r}
class(dim(df4))
```
```{r}
class(dimnames(df1))
```
```{r}
class(dimnames(df2))
```
```{r}
class(dimnames(df3))
```
```{r}
class(dimnames(df4))
```
```{r}
summary(df1)
```
```{r}
summary(df2)
```
```{r}
summary(df3)
```
```{r}
summary(df4)
```

```{r}
summary(df1$Total)
```
```{r}
summary(df1$Day1)
```
```{r}
summary(df1$Day2)
```
```{r}
summary(df1$Day3)
```
```{r}
summary(df1$Day4)
```
```{r}
summary(df1$Day5)
```
```{r}
summary(df1$Day6)
```
```{r}
summary(df1$Day7)
```

```{r}
summary(df2$AtkWins)
```
```{r}
summary(df2$DefWins)
```


```{r}
summary(df3$Total)
```
```{r}
summary(df3$Day1)
```
```{r}
summary(df3$Day2)
```
```{r}
summary(df3$Day3)
```
```{r}
summary(df3$Day4)
```
```{r}
summary(df3$Day5)
```
```{r}
summary(df3$Day6)
```
```{r}
summary(df3$Day7)
```


```{r}
summary(df4$Maps)
```
```{r}
summary(df4$K)
```
```{r}
summary(df4$D)
```
```{r}
summary(df4$A)
```
```{r}
summary(df4$KD)
```
```{r}
summary(df4$KDA)
```

```{r}
mean(df4$Maps)
```
```{r}
mean(df4$K)
```
```{r}
mean(df4$D)
```
```{r}
mean(df4$A)
```
```{r}
mean(df4$KD)
```
```{r}
mean(df4$KDA)
```


```{r}
median(df4$Maps)
```
```{r}
median(df4$K)
```
```{r}
median(df4$D)
```
```{r}
median(df4$A)
```
```{r}
median(df4$KD)
```
```{r}
median(df4$KDA)
```


```{r}
sd(df4$Maps)
```
```{r}
sd(df4$K)
```
```{r}
sd(df4$D)
```
```{r}
sd(df4$A)
```
```{r}
sd(df4$KD)
```
```{r}
sd(df4$KDA)
```
`

```{r}
var(df4$Maps)
```
```{r}
var(df4$K)
```
```{r}
var(df4$D)
```
```{r}
var(df4$A)
```
```{r}
var(df4$KD)
```
```{r}
var(df4$KDA)
```



```{r}
quantile(df4$Maps)
```
```{r}
quantile(df4$K)
```
```{r}
quantile(df4$D)
```
```{r}
quantile(df4$A)
```
```{r}
quantile(df4$KD)
```
```{r}
quantile(df4$KDA)
```





```{r}
tdf= attach(df1)
tdf
```


```{r}
df1[3,3]
```
```{r}
df2[3,3]
```
```{r}
df3[3,3]
```
```{r}
df4[3,3]
```

```{r}
head(as.matrix(df1))
```
```{r}
head(as.matrix(df2))
```
```{r}
head(as.matrix(df3))
```
```{r}
head(as.matrix(df4))
```

```{r}
tail(as.matrix(df1))
```
```{r}
tail(as.matrix(df2))
```
```{r}
tail(as.matrix(df3))
```
```{r}
tail(as.matrix(df4))
```



```{r}
is.table(df1)
```
```{r}
is.table(df2)
```
```{r}
is.table(df3)
```
```{r}
is.table(df4)
```

```{r}
is.data.frame(df1)
```
```{r}
is.data.frame(df2)
```
```{r}
is.data.frame(df3)
```
```{r}
is.data.frame(df4)
```
```{r}
is.character(df1)
```
```{r}
is.character(df2)
```
```{r}
is.character(df3)
```
```{r}
is.character(df4)
```
```{r}
if(class(df1) == 'data.frame') TRUE else FALSE
```
```{r}
if(class(df2) == 'data.frame') TRUE else FALSE
```
```{r}
if(class(df3) == 'data.frame') TRUE else FALSE
```
```{r}
if(class(df4) == 'data.frame') TRUE else FALSE
```


```{r}
stem(df4$Maps, scale=10)
```
```{r}
stem(df4$K, scale=10)
```
```{r}
stem(df4$D, scale=10)
```
```{r}
stem(df4$A, scale=10)
```


```{r}
seq_along(df2)
```
```{r}
seq_along(df3)
```
```{r}
seq_along(df4)
```


```{r}
wilcox.test(df4$Maps, df4$K)
```
```{r}
wilcox.test(df4$Maps, df4$D)
```
```{r}
wilcox.test(df4$Maps, df4$A)
```
```{r}
wilcox.test(df4$Maps, df4$KD)
```
```{r}
wilcox.test(df4$Maps, df4$KDA)
```

```{r}
apply(df1[ ,2:3],2 ,mean)
```
```{r}
apply(df2[ ,2:3],2 ,mean)
```
```{r}
apply(df3[ ,2:3],2 ,mean)
```

```{r}
apply(df1[ , 2:3], 2, var)
```
```{r}
apply(df2[ , 2:3], 2, var)
```
```{r}
apply(df3[ , 2:3], 2, var)
```


```{r}
head(na.omit(df1))
```
```{r}
head(na.omit(df2))
```
```{r}
head(na.omit(df3))
```
```{r}
head(na.omit(df4))
```
```{r}
tail(na.omit(df1))
```
```{r}
tail(na.omit(df2))
```
```{r}
tail(na.omit(df3))
```
```{r}
tail(na.omit(df4))
```

```{r}
objects(df1)
```
```{r}
objects(df2)
```
```{r}
objects(df3)
```
```{r}
objects(df4)
```
```{r}
formula(df1)
```
```{r}
formula(df2)
```
```{r}
formula(df3)
```
```{r}
formula(df4)
```

```{r}
nlevels(df1)
```
```{r}
nlevels(df2)
```
```{r}
nlevels(df3)
```
```{r}
nlevels(df4)
```

```{r}
library(ggplot2)
```



```{r}
plot(density(df4$Maps))
```
```{r}
plot(density(df4$K))
```
```{r}
plot(density(df4$D))
```
```{r}
plot(density(df4$A))
```
```{r}
plot(density(df4$KD))
```
```{r}
plot(density(df4$KDA))
```




